spring:
  security:
    user:
      name: ${config_username}
      password: ${config_password}
  cloud:
    config:
      server:
        git:
          timeout: 10
          uri: ${config_git_url}
          default-label: main
          ignoreLocalSshSettings: true
          search-paths:
            - commons
          # gerar com o comando: ssh-keygen -m PEM -t rsa -b 4096
          privateKey: ${config_private_key}

