server:
  port: ${server_port:8080}
spring:
  security:
    user:
      name: ${config_username}
      password: ${config_password}
      roles:
       - 'ACTUATOR_ADMIN'
  cloud:
    config:
      server:
        git:
          timeout: 10
          uri: ${config_git_url}
          default-label: main
          ignoreLocalSshSettings: true
          search-paths:
            - commons # Permite ter um diretorio chamando commons para ler aquivos de configurações
            - '{application}' # Permite ler arquivos separados em direotiros para cada aplicação
          # gerar com o comando: ssh-keygen -m PEM -t rsa -b 4096
          privateKey: ${config_private_key}

# Configuração do actuator para mostrar detalhes
management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    metrics:
      sensitive: false
    web:
      exposure:
        include: "*"


